name: LangSmith Integration

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    timeout-minutes: 4320
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Install dependencies
        run: |
          npm install langsmith openai

      - name: Run PR Agent
        env:
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}  # LangSmith API key
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Make sure to store your OpenAI API key as a secret
        run: |
          # Add script for interacting with LangSmith or related tasks
          # For example, log basic PR info to LangSmith or analyze files
          npx langsmith analyze --model "gpt-4" --pr-url "${{ github.event.pull_request.html_url }}" --api-key "${{ secrets.LANGSMITH_API_KEY }}"

      - name: Apply Compression Settings
        run: |
          echo "Applying compression settings and tools..."
          echo "pr_compression: enabled=true" >> .github/workflows/pr_agent.yml
          echo "improve_tool: extended_mode=true" >> .github/workflows/pr_agent.yml
         # echo "allow_only_specific_folders: [\"routes"]" >> .github/workflows/pr_agent.yml
