on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@v0.26
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Models
          model: "gpt-4o-2024-11-20"
          fallback_models: "gpt-4o-2024-08-06"
          # model_weak: "gpt-4o-mini-2024-07-18" # Optional weaker model
          # CLI
          git_provider: "github"
          publish_output: true
          publish_output_progress: true
          publish_output_no_suggestions: true
          verbosity_level: 0
          use_extra_bad_extensions: false
          # Configurations
          use_wiki_settings_file: true
          use_repo_settings_file: true
          use_global_settings_file: true
          disable_auto_feedback: false
          ai_timeout: 120
          
          # Token limits
          max_description_tokens: 500
          max_commits_tokens: 500
          max_model_tokens: 32000
          custom_model_max_tokens: -1
          # Patch extension logic
          
          allow_dynamic_context: true
          max_extra_lines_before_dynamic_context: 8
          patch_extra_lines_before: 3
          patch_extra_lines_after: 1
          secret_provider: ""
          cli_mode: false
          ai_disclaimer_title: ""
          ai_disclaimer: ""
          output_relevant_configurations: false
          large_patch_policy: "clip"
          duplicate_prompt_examples: false
          # Seed
          seed: -1
          temperature: 0.2
         
          # Other configurations
          is_auto_command: false
          enable_ai_metadata: false
