name: Build and Scan with Trivy

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'qa'
      - 'test'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'qa'
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for Docker image to be pushed to GHCR (Optional)
        run: |
          echo "Waiting for Docker image to be available..."
          sleep 10 # Optional delay for ensuring the image is available

      - name: Run Trivy Scan on Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
