name: CI Pipeline with Trivy Scan

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/syrinezioudi/nodejs-demo:latest .
      
      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/syrinezioudi/nodejs-demo:latest

      # Run Trivy scan
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.2.2
        with:
          image: ghcr.io/syrinezioudi/nodejs-demo:latest
