name: Build, Scan with Trivy & Update DB

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'qa'
      - 'test'
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'package.json'

  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'qa'
      - 'test'

  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (weekly)
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar zxvf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Cache Trivy Database
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Update Trivy Database
        run: trivy --download-db-only

      - name: Run Trivy Scan on Docker Image
        run: |
          trivy image --format table --exit-code 1 --severity CRITICAL,HIGH ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  update-trivy-db:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar zxvf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Cache Trivy Database
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Update Trivy Database
        run: trivy --download-db-only
